version: '3.8'

services:
  db:
    image: postgres
    environment:
      POSTGRES_DB: eventos_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: Tusdatos**
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  backend:
    build:
      context: ../BackEndMisEventos
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      DATABASE_URL: postgresql://postgres:Tusdatos**@db/eventos_db

  frontend:
    build:
      context: ../../frontend/FrontendMisEventos
    ports:
      - "8080:80"
    depends_on:
      - backend

volumes:
  postgres_data:
